### ISSUE TITLE
Some __repr__ methods are returning bytes, not strings

### ISSUE THREAD

**Issue by funkybob** [cackharot/suds-py3#1]
Was just kicking around in a client.Client, and the following:

```
>>> cc.sd[0].types
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: __repr__ returned non-string (type bytes)
>> cc.sd[0].ports
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: __repr__ returned non-string (type bytes)
```

Having seen the nightmarish state mainline suds is in, I'm impressed you even got this working in the first place :)

**Comment by cackharot** [comment]
Fixed at ![commit](https://github.com/cackharot/suds-py3/commit/303679cf6cbd150d9e4d8d0c44ba80e0b637b1b2)
