### ISSUE TITLE
Cannot create more than 2 Clients with the same wsdl

### ISSUE THREAD

**Issue by dpzx** [cackharot/suds-py3#16]
I cannot create more than 2 Clients because it will not load the xsd because it thinks that it is already imported

/suds/xsd/schema.py

diff between 1.2 and 1.3.1

version 1.2
 def open_imports(self, options):
        """
        Instruct all contained L{sxbasic.Import} children to import
        the schema's which they reference.  The contents of the
        imported schema are I{merged} in.
        @param options: An options dictionary.
        @type options: L{options.Options}
        """
        for imp in self.imports:
            imported = imp.open(options)
            if imported is None:
                continue
            imported.open_imports(options)
            log.debug('imported:\n%s', imported)
            self.merge(imported)

version 1.3.1
 __already_imported = {}

def open_imports(self, options):
        """
        Instruct all contained L{sxbasic.Import} children to import
        the schema's which they reference.  The contents of the
        imported schema are I{merged} in.
        @param options: An options dictionary.
        @type options: L{options.Options}
        """
        for imp in self.imports:
            if imp.location:
                self.__already_imported.setdefault(imp.location, 0)
                if self.__already_imported[imp.location] > 1:
                    continue
                self.__already_imported[imp.location] += 1

            imported = imp.open(options)
            if imported is None:
                continue
            imported.open_imports(options)
            log.debug('imported:\n%s', imported)
            self.merge(imported)

-bash-4.1$ python test_suds.py

0x7ff21f982390    (Client 1 address)
0x7ff2203ab448   (self.__already_imported)
0
0x7ff21f8f4a90     (Client 2 address)
0x7ff2203ab448   (self.__already_imported)
1
0x7ff21f7dd160    (Client 3 address)
0x7ff2203ab448   (self.__already_imported)
2

Traceback (most recent call last):
  File "test_suds.py", line 7, in <module>
    client3 = Client(wsdl)
  File "/opt/python/lib/python3.5/site-packages/suds/client.py", line 111, in __init__
    self.wsdl = reader.open(url)
  File "/opt/python/lib/python3.5/site-packages/suds/reader.py", line 152, in open
    d = self.fn(url, self.options)
  File "/opt/python/lib/python3.5/site-packages/suds/wsdl.py", line 159, in __init__
    self.set_wrapped()
  File "/opt/python/lib/python3.5/site-packages/suds/wsdl.py", line 264, in set_wrapped
    raise TypeNotFound(query.ref)
suds.TypeNotFound: Type not found: '(getState, http://blah.blah/, )'

**Comment by cackharot** [comment]
I can able to define multiple clients for the same or different WSDL.

Can you provide your test code?

Thanks,

**Comment by dpzx** [comment]
you gotta do one more than 2 clients. Try doing a third c3

c1 = Client("http://localhost:8181/soap/helloservice?wsdl", username='bob', password='catbob')
c2 = Client("http://localhost:8181/soap/helloservice?wsdl", username='bob', password='catbob')
c3 = Client("http://localhost:8181/soap/helloservice?wsdl", username='bob', password='catbob')

**Comment by dpzx** [comment]
btw our web services is jax-ws and I can consistently reproduce the issue.

**Comment by dpzx** [comment]
another point to note is we do not directly define the schema in the wsdl so it will need to be imported in.

**Comment by elsampsa** [comment]
I have a similar(ish) problem:

>from suds.client import Client
>from suds.cache import ObjectCache, NoCache
>
>url="file:///home/sampsa/live555/py_nvr/onvif/wsdl/devicemgmt.wsdl" 
>xaddr="http://192.168.1.8:8080/onvif/device_service"
>
>cl1=Client(url,location=xaddr,cache=NoCache(),headers={'Content-Type': 'application/soap+xml'})
>
>cl2=Client(url,location=xaddr,cache=NoCache(),headers={'Content-Type': 'application/soap+xml'})

The  first client cl1 initializes ok, but for the second one I get

>suds.TypeNotFound: Type not found: '(contentType, http://www.w3.org/2005/05/xmlmime, )'

**Comment by dpzx** [comment]
The attribute '.__already_imported' is not in the class contructor and so it is a static member which causes this issue when the schema needs to be imported in from a file.
Can we fix this issue or do I have to provide proof?

**Comment by cackharot** [comment]
Should be fixed now. Sorry for taking long time to fix this.

**Comment by dpzx** [comment]
Thank you sir.
