### ISSUE TITLE
Not working with NTLM Auth

### ISSUE THREAD

**Issue by Orangensaft** [cackharot/suds-py3#19]
This Version is not working with NTLM Auth because it uses the package python-ntlm, which is not compatible with python3.

A working fix would be replacing line 94 in file transport.https:

`from ntlm import HTTPNtlmAuthHandler`

with 

`from ntlm3 import HTTPNtlmAuthHandler`

So it uses the python-ntlm3 Package, which works with python3.

I've already created a pull-request for that: #20

**Comment by cackharot** [comment]
Thanks for the PR. #20 has been merged. Hence closing this issue.
