### ISSUE TITLE
Documentation hosting

### ISSUE THREAD

**Issue by hsmett** [cackharot/suds-py3#25]
Hi!
fedorahosted.org was retired on march 1st:
[https://fedoraproject.org/wiki/Infrastructure/Fedorahosted-retirement](https://fedoraproject.org/wiki/Infrastructure/Fedorahosted-retirement)
You'll have to host your documentation elsewhere :(

**Comment by hsmett** [comment]
Where can we find the documentation nowadays?

**Comment by cackharot** [comment]
I have hosted a copy of the documentation I could scrap off at 

https://suds-py3.readthedocs.io/en/latest/

Will improve it over time. **Expecting the community support :)**
