### ISSUE TITLE
Addition dot getting added along with Host Name

### ISSUE THREAD

**Issue by VenkataRN** [cackharot/suds-py3#27]
(Pdb) tasClient = Client("http://172.16.198.20:1234/Tiger/TigerApplicationService/?wsdl")
(Pdb) tsls = tasClient.service.GetTslList()
(Pdb) p tsls[0][0]
http://swpc2.:1234/Tiger/TSL/Instance0

If you observer a dot "." got added before ":1234"

$ cat /etc/hosts | grep 172.16.198.20 

172.16.198.20    swpc2       swpc2

**Comment by cackharot** [comment]
I don't understand the issue here. Can you give more details or sample code?

Thanks,

**Comment by cackharot** [comment]
@VenkataRN Seems the value your are printing is coming from the WSDL service method response.
tsls = tasClient.service.GetTslList() ## this is your WSDL method
(Pdb) p tsls[0][0] ## <- what you print isn't the response?

This is not the issue from the library.
