### ISSUE TITLE
Rondom (mostly too long) response times when using static IP

### ISSUE THREAD

**Issue by Devligue** [cackharot/suds-py3#28]
Hi. Please consider following  simple code:

```
from suds.client import Client

client = Client(url=WSDL_PATH, timeout=15)
client.set_options(location=TARGET_HOST)

request_data = client.factory.create('RequestName')

response = client.service.methodName(request_data)
```

Everything works perfect and fast when the target device (target_host) is connected to network and my pc is connected to the (same) network. But when I set a static IP on my pc and connect directly to the host device with cable (i.e. neither device nor pc have internet access but both can access each other by ip), something strange happens. Of course the script still works, but the response time is sometimes instant (as expected) and sometimes it takes 10 seconds. But most of the time it takes even more or it just fails due to timeout. There is no rule - every time it is different. Normally I would expect it to work instantly since there is no middle-device, just two devices connected directly. In facet, when I ping target host from pc (from command line) the response is always instant, so I am almost certain this is python/suds fault.

For comparison if I construct the soap request 'manually', open the socket with target host ip and then send the request I get instant response. That suggests that  it is something in suds or some package it relies on.

**Comment by cackharot** [comment]
Can you try profiling the script? This might give you some insight which part of code is slow.
Example: `python -m cProfile -o out.prof your_script.py`
Install `pip install snakeviz && snakeviz out.prof` for visualization or any other tool you like.

Let me know your findings.

**Comment by Devligue** [comment]
It was some time ago and I can no longer reproduce this problem. Everything works fine now regardless of the connection method :) But if I encounter similar problem in the future I will provide you with profiling output.
