### ISSUE TITLE
Unable to install this package in python 3.6

### ISSUE THREAD

**Issue by SanthoshAshokkumar** [cackharot/suds-py3#38]
I have a dependency to install this package for PyDatastream
https://github.com/vfilimonov/pydatastream/blob/master/README.md. I am currently using python 3.6 through miniconda and Pycharm is my IDE. I am not able to install this package for python 3.6. Kindly help with this.!

**Comment by cackharot** [comment]
@SanthoshAshokkumar  Could you post the error? It would help me to diagnose. Remember to install using `pip3 install suds-py3`
