### ISSUE TITLE
Client overrides method-specific location URL

### ISSUE THREAD

**Issue by tuukkamustonen** [cackharot/suds-py3#42]
In https://github.com/cackharot/suds-py3/blob/master/suds/client.py#L107 the URL from which WSDL was loaded is stored as `location` in options:

```python
self.options.location = url
```

When invoking requests, this URL is then loaded up and preferred over method-specific URL specified in SOAP response in https://github.com/cackharot/suds-py3/blob/master/suds/client.py#L634:

```python
location = self.location()
```

I load wsdl from `https://somehost/somepath?wsdl` but SOAP requests must be sent without the query parameter so to `https://somehost/somepath`. The code in https://github.com/cackharot/suds-py3/blob/master/suds/client.py#L107 causes the URL with `?wsdl` getting sent instead.

To workaround that, I cleared the location after initializing Suds `Client`:

```python
client = Client(...)
client.options.location = None
```

This allows `self.location()` lookup to return `self.method.location` instead.

However, on python 3 `urllib.request` operations (that suds uses to load up WSDL) seem to return `bytes` not `str`. This leads to `self.method.location` being `bytes` and not `str`. However, the calls itself (to actually perform SOAP operation) in `urllib.request` expect URL to be `str` not `bytes`. So my calls fail.

My question here would be: why is https://github.com/cackharot/suds-py3/blob/master/suds/client.py#L107 line added in `suds-py3` (it doesn't exist in original `suds` library). Is it intentional or accident, and what might the reasoning be?

I assume the line shouldn't be there, and code should instead `decode()` the URL that is sent to `urllib.request.urlopen` (or `urllib.request.OpenerDirector.open()`) instead?

(Disclaimer: I am not SOAP expert by any mean, merely trying to migrate an old project from py2->py3.)

**Comment by cackharot** [comment]
PR #40  will fix this issue. I'm merging that shortly and do release.

**Comment by cackharot** [comment]
New PyPi release.
https://pypi.org/manage/project/suds-py3/release/1.3.4.0/
