### ISSUE TITLE
Use of setLocation causes later AttributeError: 'str' object has no attribute 'decode'

### ISSUE THREAD

**Issue by hatchjdecho** [cackharot/suds-py3#45]
In wsdl.py  when using the method Service.setLocation() to override a wrong location in the wsdl it stores the raw string. _(line 860: m.location = url)_

However the method SoapClient.location in client.py uses self.method.location.decode('utf-8')
This is compatible with the Port.__init__ which sets the self.location  with .encode('utf-8')

So when trying to use the service after using setLocation() the string fails to decode with the error in the title.

I believe the correct fix would be to change Service.setLocation() in wsdl.py at line 860 to use m.location = url.encode('utf-8').

Cheers 
James.

**Comment by cackharot** [comment]
Merged will release a new version along with other non breaking fixes.
