### ISSUE TITLE
Unicode string handling in Windows

### ISSUE THREAD

**Issue by trackvsb** [cackharot/suds-py3#6]
Hello,

Thank you for publishing the package. I am migrating from suds, written for Python < 3.0. Decided to try your package and now I am having difficulties installing it in Python 3.2.

All my work is done on Windows 7. 

What I noticed is that, in general, scripts containing unicode manipulations fail to compile in IDLE. As an example, files attribute.py and text.py fail.

As a workaround, I started making some changes in sax/text.py and setup.py. For instance, I replaced

joined = u''.join((self, other))

with 

joined = ''.join((self, other))

and made the corresponding change in setup.py.

Then I realized that more changes will be necessary.

I understand that some modules may be written by different people - like the 2 modules above were written by Jeff Ortel probably to run on Linux. Do you plan on modifying/generalizing the package to make it work on Windows?

Best regards,
~trackvsb

**Comment by cackharot** [comment]
Hi,

Thanks for your interest.

I'm planing on revisiting this package and make proper effort to make it work in python 3.2 and windows.

Look out for changes in the coming weeks.

Cheers,

**Comment by cackharot** [comment]
Made some updates and tested on Windows 8 and Python 3.3.2

Would be helpful if you could test them out at your end.

Note: Have a look at the README.md file examples section.
