### ISSUE TITLE
cannot process href in build_catalog in multiref.py

### ISSUE THREAD

**Issue by seeman1978** [cackharot/suds-py3#67]
![20200925_173508](https://user-images.githubusercontent.com/34470931/94335359-c5521d80-000d-11eb-8a9e-3c166ff87a91.jpg)
The soap response message likes the snapshot. Suds cannot process href.

source code
    def build_catalog(self, body):        
        for child in body.children:
            if self.soaproot(child):
                self.nodes.append(child)
            id = child.get('id')
            if id is None:
                continue
            key = '#%s' % id
            self.catalog[key] = child
I think recurse invoke build_catalog can resolve this problem.
I modified.
def build_catalog(self, body):        
        for child in body.children:
            if self.soaproot(child):
                self.nodes.append(child)
            id = child.get('id')
            if id is None:
                self.build_catalog(child)
            else
                key = '#%s' % id
                self.catalog[key] = child

**Comment by cackharot** [comment]
Merged the fix PR and release @ https://pypi.org/project/suds-py3/1.4.3.0/
