### ISSUE TITLE
release a wheel on pypi

### ISSUE THREAD

**Issue by graingert** [cackharot/suds-py3#80]
please release a wheel on pypi: `python -m build --sdist --wheel && twine upload dist/*`

**Comment by cackharot** [comment]
Done.
https://pypi.org/project/suds-py3/1.4.5.0/

**Comment by lociii** [comment]
@cackharot what else is changed in 1.4.5.0? Would you mind adding a changelog or at least tag the release?
The source is still at [1.4.4.1](https://github.com/cackharot/suds-py3/blob/1d92cc6297efee31bfd94b50b99c431505d7de21/suds/__init__.py#L28) which makes proper dependency management quite hard. 
Thank you.

**Comment by cackharot** [comment]
No changes. Commit tagged in git.
